import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  LOG_LEVEL: z.string().optional(),
  PORT: z.coerce.number().default(3002),
  DATABASE_URL: z.string().min(1),
  CORS_ORIGINS: z.string().optional(),
  JWT_SECRET: z.string().min(1).optional(),
  AUTH_COOKIE_NAME: z.string().default('bck_auth'),
  AUTH_COOKIE_MAX_AGE: z.coerce.number().default(86400),
  AUTH_TOKEN_TTL: z.string().optional(),
  STAFF_PORTAL_CODE: z.string().optional(),
  STAFF_COOKIE_NAME: z.string().default('bck_staff'),
  STAFF_COOKIE_MAX_AGE: z.coerce.number().default(28800),
  COOKIE_SECURE: z.coerce.boolean().default(false),
  COOKIE_SAMESITE: z.string().default('Lax'),
  COOKIE_DOMAIN: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  DELIVERY_WEBHOOK_TOKEN: z.string().optional(),
  MAKE_WEBHOOK_URL: z.string().optional(),
  MAKE_VOICE_WEBHOOK_URL: z.string().optional(),
  AI_WORKFLOW_ID: z.string().optional(),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().optional(),
  GROQ_API_KEY: z.string().optional(),
  ELEVENLABS_API_KEY: z.string().optional(),
  ELEVENLABS_AGENT_ID: z.string().optional(),
  ELEVENLABS_AGENT_URL: z.string().optional(),
  ELEVENLABS_VOICE_ID: z.string().optional(),
  ELEVENLABS_MODEL_ID: z.string().optional(),
  ELEVENLABS_OUTPUT_FORMAT: z.string().optional(),
  ELEVENLABS_VOICE_STABILITY: z.string().optional(),
  ELEVENLABS_VOICE_SIMILARITY: z.string().optional(),
  ELEVENLABS_VOICE_STYLE: z.string().optional(),
  ELEVENLABS_SPEAKER_BOOST: z.string().optional(),
  GMAIL_USER: z.string().optional(),
  GMAIL_APP_PASSWORD: z.string().optional(),
  CUSTOMER_URL: z.string().optional(),
  REVIEW_ACCESS_TOKEN_REQUIRED: z.string().optional(),
  REVIEW_ACCESS_TOKEN_TTL_MINUTES: z.string().optional(),
  REVIEW_ACCESS_TOKEN_RETURN: z.string().optional(),
  TABLET_QUESTION_LIMIT: z.string().optional(),
  TABLET_WARNING_AFTER_MS: z.string().optional(),
  TABLET_EXPIRE_AFTER_MS: z.string().optional(),
  ALLOW_LEGACY_ORDERS: z.string().optional(),
});

export type Env = z.infer<typeof envSchema>;
